### ISSUE TITLE
Can not install unbound from epel

### ISSUE THREAD

**Issue by mnagaku** [classmethod-aws/fullbok#10]
JST5/13夜まではデプロイできていたのですが、JST5/17夜にデプロイできなくなっていました。
slaveの構築の途中で止まっているようで、slave内のログを見ると、unboundのインストールに失敗していました。
amazonlinuxなのでRHEL6系のepelを見に行くと思うのですが、
http://unbound.jp/unbound/packages/
RHEL6ではunboundはextraだとされており、JST5/18時点でepel内にunboundは入っていないようです。
http://dl.fedoraproject.org/pub/epel/6/x86_64/
cloudformationを分かっていないので外しているかもですが...

**Comment by noto-satoshi** [comment]
@mnagaku さん

こちら返信できず申し訳ありません。また、ご報告および #12 についてもありがとうございました。#12 にもコメントした通りunboundが現時点でcentos6のextraに移動したため #15 をマージしています。
