### ISSUE TITLE
起動したクラスターのEC2に自動でタグを付ける

### ISSUE THREAD

**Issue by satoshi7** [classmethod-aws/fullbok#14]
JMeterクラスター（単一Master+複数Slave）について、複数起動することがある。
この場合、どのSlaveがどのMasterに属しているか分からなくなるため、起動時に自動でタグを付けることで、間違いを無くす。さらに、Master側では、タグを頼りにSlaveのホスト名一覧を取得できれば、手組みでのホスト登録が無くなる。

**Comment by noto-satoshi** [comment]
#19 が対応しているかと思います。ご確認下さい。
